Update to Less v2.5.1 to fix viewing index.html from local filesystem
Previously opening index.html from the local filesystem (eg for testing)
resulted in the JS error:
Error: Couldn't load file:///.../fileit/index.less

This does not occur with newer versions of Less.